/* Shared site layout: navigation, footer, back-to-top button, and lazy loading. */
document.addEventListener('DOMContentLoaded', () => {
  const prefix = [...document.scripts].find(s => s.getAttribute('src')?.includes('js/layout.js'))?.getAttribute('src')?.startsWith('../') ? '../' : './';
  const header = document.getElementById('header-placeholder');
  const footer = document.getElementById('footer-placeholder');
  if (header) header.innerHTML = `<header class="header"><div class="container header-content"><a class="logo" href="${prefix}" aria-label="KE Bill Guide home"><span>KE Bill Guide</span></a><button class="mobile-menu-btn" type="button" aria-controls="site-nav" aria-expanded="false">Menu</button><nav class="nav" id="site-nav" aria-label="Primary navigation"><a href="${prefix}">Bill Guide</a><a href="${prefix}electricity-bill-calculator/">Calculator</a><a href="${prefix}k-electric-unit-price/">Tariff Rates</a><a href="${prefix}k-electric-payment-methods/">Payments</a><a href="${prefix}k-electric-support/">Support</a><a href="${prefix}about-us/">About</a></nav></div></header>`;
  if (footer) footer.innerHTML = `<footer class="footer"><div class="container footer-content"><div><h2>KE Bill Guide</h2><p>Independent educational resource and utility tools for K-Electric consumers. Not affiliated with K-Electric.</p></div><div><h3>Help & Tools</h3><a href="${prefix}electricity-bill-calculator/">Bill Calculator</a><a href="${prefix}k-electric-unit-price/">Unit Prices & Tariff Slabs</a><a href="${prefix}k-electric-payment-methods/">Payment Methods</a><a href="${prefix}k-electric-support/">Customer Support & Complaints</a><a href="${prefix}k-electric-new-connection/">New Connection Guide</a><a href="${prefix}k-electric-net-metering/">Net Metering Guide</a><a href="${prefix}k-electric-load-shedding/">Load Shedding Info</a></div><div><h3>About & Policy</h3><a href="${prefix}about-us/">About Us</a><a href="${prefix}contact/">Contact Us</a><a href="${prefix}editorial-guidelines/">Editorial Guidelines</a><a href="${prefix}fact-checking-policy/">Fact-Checking Policy</a></div><div><h3>Legal Policies</h3><a href="${prefix}privacy-policy/">Privacy Policy</a><a href="${prefix}terms-and-conditions/">Terms & Conditions</a><a href="${prefix}disclaimer/">Disclaimer</a><a href="${prefix}cookie-policy/">Cookie Policy</a></div></div><div class="footer-bottom"><p>© <span class="dynamic-year"></span> KE Bill Guide. Independent of K-Electric. For account-specific official billing and services, visit <a href="https://www.ke.com.pk/" rel="noopener noreferrer">K-Electric’s Official Website</a>.</p></div></footer>`;
  document.querySelectorAll('.dynamic-year').forEach(el => el.textContent = new Date().getFullYear());
  document.querySelectorAll('img').forEach(img => { img.loading = 'lazy'; img.decoding = 'async'; });
  const button = document.querySelector('.mobile-menu-btn');
  const nav = document.getElementById('site-nav');
  button?.addEventListener('click', () => { const open = nav.classList.toggle('active'); button.setAttribute('aria-expanded', String(open)); });
  const back = document.createElement('button');
  back.className = 'back-to-top'; back.type = 'button'; back.setAttribute('aria-label', 'Back to top'); back.textContent = '↑';
  back.addEventListener('click', () => window.scrollTo({top: 0, behavior: 'smooth'})); document.body.append(back);
  window.addEventListener('scroll', () => back.classList.toggle('visible', scrollY > 500), {passive: true});
});
